#!/usr/bin/env bash

## Lint module code.
##
## Usage: fin run-lint [module]

fin yarn lint:yaml "../modules/contrib/$1" --fix
fin yarn lint:js "../modules/contrib/$1/**/*.es6.js" --fix
fin yarn lint:css "../modules/contrib/$1/**/*.css" --fix
