#!/usr/bin/env bash

## Reset Drupal repository.
##
## Usage: fin run-reset [project]

fin composer require drupal/"$1" --no-update --no-interaction
rm -rf web/modules/contrib/"$1" && fin composer install --no-interaction
fin drush cr
