#!/usr/bin/env bash

## Run validation tools.
##
## Usage: fin run-validate [project]

fin yarn lint:js "../modules/contrib/$1/**/*.es6.js"
fin yarn lint:css "../modules/contrib/$1/**/*.css"
fin yarn lint:yaml "../modules/contrib/$1"
fin blt validate:phpcs
