#!/usr/bin/env bash

## Clone Drupal repository.
##
## Usage: fin run-clone [project] [git-url]

fin composer require drupal/"$1" --no-update --no-interaction
rm -rf web/modules/contrib/"$1" && git clone "${2:-"git@git.drupal.org:project/$1"}" web/modules/contrib/"$1"
fin drush cr
